spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sk_example_user
    password: password

server:
  port: 8080

sk-example:
  json:
    obj-key: current